### ISSUE TITLE
华为报错 请问何解？

### ISSUE THREAD

**Issue by kkss2020** [hyue418/taobao-11-11#109]
/E: Wrapped java.lang.IllegalArgumentException: Path bounds must not be negative (<init>#30)
Wrapped java.lang.IllegalArgumentException: Path bounds must not be negative
    at <init>:30:0
    at smlMove (/storage/emulated/0/脚本/淘宝+京东双十一活动脚本.js:485:0)
    at randomSwipe (/storage/emulated/0/脚本/淘宝+京东双十一活动脚本.js:430:0)
    at /storage/emulated/0/脚本/淘宝+京东双十一活动脚本.js:217:0
    at runTaobao (/storage/emulated/0/脚本/淘宝+京东双十一活动脚本.js:157:0)
    at /storage/emulated/0/脚本/淘宝+京东双十一活动脚本.js:102:0
    at runOptions (/storage/emulated/0/脚本/淘宝+京东双十一活动脚本.js:96:0)
    at taskChoose (/storage/emulated/0/脚本/淘宝+京东双十一活动脚本.js:68:0)
    at /storage/emulated/0/脚本/淘宝+京东双十一活动脚本.js:40:0

**Comment by kkss2020** [comment]
滑动的时候就会报错

**Comment by hyue418** [comment]
看样子像是获取设备宽高错误了，可以自己在代码手动设置一下。
