### ISSUE TITLE
2.4.0 版本京东全民营业bug

### ISSUE THREAD

**Issue by CosmoGao** [hyue418/taobao-11-11#159]
Wrapped Java.lang.ArrayIndexOutOFBoundsException.lenth=1;index=1 #314

**Comment by zheng-wb** [comment]
> Wrapped Java.lang.ArrayIndexOutOFBoundsException.lenth=1;index=1 #314

我也一样

**Comment by ali5199** [comment]
240我也不能运行

**Comment by maple0917** [comment]
2.4.0京东一样无法运行，错误代码
Wrapped java.lang.ArrayIndexOutOfBoundsException: length=1; index=1 (/storage/emulated/0/脚本/taobao-11-11-master/淘宝+京东双十一活动脚本.js#314)
Wrapped java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
    at /storage/emulated/0/脚本/taobao-11-11-master/淘宝+京东双十一活动脚本.js:314:0
    at runJd (/storage/emulated/0/脚本/taobao-11-11-master/淘宝+京东双十一活动脚本.js:297:0)
    at /storage/emulated/0/脚本/taobao-11-11-master/淘宝+京东双十一活动脚本.js:116:0
    at runOptions (/storage/emulated/0/脚本/taobao-11-11-master/淘宝+京东双十一活动脚本.js:92:0)
    at taskChoose (/storage/emulated/0/脚本/taobao-11-11-master/淘宝+京东双十一活动脚本.js:64:0)
    at /storage/emulated/0/脚本/taobao-11-11-master/淘宝+京东双十一活动脚本.js:36:0

**Comment by hyue418** [comment]
已修复，请更新2.4.1
