### ISSUE TITLE
运行到滑动屏幕时报错

### ISSUE THREAD

**Issue by pillar0406** [hyue418/taobao-11-11#76]
我全文复制的代码，然后每次运行到屏幕显示滑啊滑的时候就报错，自动结束了

**Comment by pillar0406** [comment]
E: Wrapped java.lang.IllegalArgumentException: Path bounds must not be negative (<init>#30)
Wrapped java.lang.IllegalArgumentException: Path bounds must not be negative
    at <init>:30:0
    at smlMove (/storage/emulated/0/脚本/双十一.js:485:0)
    at randomSwipe (/storage/emulated/0/脚本/双十一.js:430:0)
    at /storage/emulated/0/脚本/双十一.js:188:0
    at runTaobao (/storage/emulated/0/脚本/双十一.js:157:0)
    at /storage/emulated/0/脚本/双十一.js:114:0
    at runOptions (/storage/emulated/0/脚本/双十一.js:96:0)
    at taskChoose (/storage/emulated/0/脚本/双十一.js:68:0)
    at /storage/emulated/0/脚本/双十一.js:40:0

**Comment by hyue418** [comment]
建议直接下js文件运行一下

**Comment by kkss2020** [comment]
同问 是滑动那个代码不行 看不懂不会改
